const { Map, List } = require("immutable")
let map1 = new Map({a: 1, b: 2, c: 3})
let map2 = map1
map2 = map2.set('a', 10)
console.log(map1.get('a'))
console.log(map2.get('a'))
console.log(map1.equals(map2))
console.log(map1 === map2)
let list = List([1, 2])
console.log(list.get('1'))
console.log(...map1)
